### ISSUE TITLE
buffer underflow error.

### ISSUE THREAD

**Issue by mahyar1284** [admiralmaggie/ESP32_BT_SRC_ADC#1]
audio quality is not good enough and repeatedly buffer underflow errors

**Comment by admiralmaggie** [comment]
@mahyar1284 It's the best I can do with the amount of RAM and processing power ESP32 has. Feel free to share your finding if you were able to improve the audio quality.

**Comment by mahyar1284** [comment]
> @mahyar1284 It's the best I can do with the amount of RAM and processing power ESP32 has. Feel free to share your finding if you were able to improve the audio quality.

can't this done completely with DMA?

**Comment by admiralmaggie** [comment]
@mahyar1284 you can definitely try converting the routines to DMA. That would improve the ADC performance but I think we would run out of memory fairly quick. Give it a shot and please share the results if you get it to work.
